sudo: false

language: java

cache:
  directories:
  - $HOME/.m2

install: true

script:
  - mvn -f Mockito_Example/pom.xml clean test jacoco:report
after_success:
  - mvn -f Mockito_Example/pom.xml coveralls:report
